name: 'Build and Zip'
description: 'Build and Zip  Extension'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build and zip extension artifact
      run: npm build -- --zip
      shell: sh
