name: 'Build and Zip'
description: 'Build and Zip  Extension'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
      shell: sh
    - name: Build and zip extension artifact
      run: npm run build -- --zip
      shell: sh
